### ISSUE TITLE
Dodawanie wydatków nie aktualizuje listy wydatków.

### ISSUE THREAD

**Issue by ADusinski** [ADusinski/Manager-Wydatkow-projekt-na-TIM#7]
Po dodaniu wydatku nie jest aktualizowana lista wydatków. Aby zobaczyć aktualną listę trzeba wcisnąć powrót do listy kategorii wydatków i ponownie wybrać kategorię, w której został dodany wydatek. Lista powinna aktualizować się automatycznie.

**Comment by jdabrowski11926** [comment]
Naprawione
