### ISSUE TITLE
Dodawanie kategorii nie aktualizuje listy kategorii.

### ISSUE THREAD

**Issue by ADusinski** [ADusinski/Manager-Wydatkow-projekt-na-TIM#9]
Po dodaniu kategori nie jest aktualizowana lista kategorii. Aby zobaczyć aktualną listę trzeba wcisnąć powrót aby sie wylogować i zalogować się ponownie. Lista powinna aktualizować się automatycznie.

**Comment by jdabrowski11926** [comment]
Naprawione
